import './globals.css'
import type { Metadata } from 'next'
import clsx from 'clsx'
import { Inter } from 'next/font/google'

import { Sidebar } from '@/components/ui/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-white')}>
        <main className="lg:grid grid-flow-col auto-cols-max h-screen max-w-screen">
          <div className="fixed h-screen hidden lg:block">
            <Sidebar />
          </div>
          <div className="lg:ml-[300px] w-full lg:w-[calc(100vw-300px)]">{children}</div>
        </main>
      </body>
    </html>
  )
}
