import './globals.css'
import type { Metadata } from 'next'
import clsx from 'clsx'
import { Inter } from 'next/font/google'
import { GiHamburgerMenu } from 'react-icons/gi'

import { Sidebar } from '@/components/ui/sidebar'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import menu from '@/lib/menu.json'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-white')}>
        <main className="lg:grid grid-flow-col auto-cols-max h-screen max-w-screen">
          <div className="fixed h-screen hidden lg:block">
            <Sidebar />
          </div>

          <div className="lg:ml-[300px] w-full lg:w-[calc(100vw-300px)]">
            <header className="h-20 flex items-center p-6 gap-4">
              <div className="block lg:hidden">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button>
                      <GiHamburgerMenu />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuLabel>Menu</DropdownMenuLabel>
                    <DropdownMenuSeparator />

                    <DropdownMenuItem>Products</DropdownMenuItem>
                    <DropdownMenuItem>Carts</DropdownMenuItem>
                    <DropdownMenuItem>Product with Dummy</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              <h1>Header</h1>
            </header>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
